### ISSUE TITLE
Is this Repo Licensed

### ISSUE THREAD

**Issue by jgrasser** [makewhatis/rhce.co#4]
Hiya, 

I was saddened to see rhce.co drop off the web a couple years ago and I would like to get it back up an and running. 

My plan is to deploy it to AppEngine. 

Before I do so, I would like to ask your permission. Are you ok if I do this?

Best wishes
Joseph G.

**Comment by makewhatis** [comment]
rhce.co is still up... is it not available for you?

**Comment by gravyboat** [comment]
@makewhatis It's up for me as well.

**Comment by jgrasser** [comment]
Did you guys change the domain ->
$ curl -I http://rhce.co/ 
curl: (6) Could not resolve host: rhce.co

**Comment by jgrasser** [comment]
Nevermind, I am to pull it up on my phone but not my laptop.

**Comment by jgrasser** [comment]
It must be some local dns issue.

**Comment by gravyboat** [comment]
@jgrasser Okay cool, I am going to close this then. Feel free to open it back up if you believe there is an issue!
